const fs = require('fs');
['src/components/BorrowerDashboard.tsx', 'src/components/LenderDashboard.tsx'].forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  // Remove the redundant headers generated by the image-to-code AI
  content = content.replace(/<header[\s\S]*?<\/header>/g, '');
  // Remove sidebars if any
  content = content.replace(/<aside[\s\S]*?<\/aside>/g, '');
  fs.writeFileSync(file, content);
});
